### 实现多元线性回归模型

In [11]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [12]:
boston = datasets.load_boston()

In [13]:
X = boston.data
print(type(X),X.shape)  # 矩阵，并不是单单一列

<class 'numpy.ndarray'> (506, 13)


In [14]:
y = boston.target
print(type(y),y.shape)  # 向量

<class 'numpy.ndarray'> (506,)


In [15]:
X=X[y<50]
y=y[y<50]

In [16]:
X.shape

(490, 13)

In [26]:
y.shape

(490,)

In [27]:
from playML.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,seed = 666)  

In [29]:
X_train
y_train.ndim  # 向量

1

In [30]:
from playML.LinearRegression import LinearRegression
reg = LinearRegression()
print(reg,type(reg))

LinearRegression() <class 'playML.LinearRegression.LinearRegression'>


In [31]:
reg.fit_normal(X_train,y_train)  # 求theta

LinearRegression()

In [32]:
reg.coef_  # 系数

array([-1.18919477e-01,  3.63991462e-02, -3.56494193e-02,  5.66737830e-02,
       -1.16195486e+01,  3.42022185e+00, -2.31470282e-02, -1.19509560e+00,
        2.59339091e-01, -1.40112724e-02, -8.36521175e-01,  7.92283639e-03,
       -3.81966137e-01])

In [33]:
reg.intercept_  # 截距

34.161435496213905

In [34]:
reg.score(X_test,y_test)  # r方

0.8129802602658359

### test

In [3]:
# 矩阵和向量点乘
a = np.arange(9).reshape(3,3)
b = np.array([1,2,3])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b.dtype

dtype('int32')

In [5]:
a.dot(b)   # b是列向量   看作行矩阵

array([ 8, 26, 44])

In [6]:
b.dot(a)   # b 是行向量  看作列矩阵

array([24, 30, 36])

In [6]:
c = np.array([[1,2,3]]).reshape(-1,1)
c

array([[1],
       [2],
       [3]])

In [7]:
np.hstack((a,c))

array([[0, 1, 2, 1],
       [3, 4, 5, 2],
       [6, 7, 8, 3]])

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
b


array([1, 2, 3])

In [10]:
np.hstack([b,a])

ValueError: all the input arrays must have same number of dimensions