In [2]:
import numpy as np

In [3]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
x[3]

3

In [5]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2]

array([3, 5, 7])

In [7]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [8]:
ind = [3,5,8]

In [9]:
x[ind]

array([3, 5, 8])

In [15]:
x1 = [i for i in range(10)]
x1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
x1[[3,4,5]]  # 原生不支持

TypeError: list indices must be integers or slices, not list

In [55]:
ind = np.array([[0,2],[1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [11]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]

array([ 1,  6, 11])

In [58]:
X[0,col]

array([1, 2, 3])

In [59]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [12]:
col = [True,False,True,True]  # 重要
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### numpy.array 的比较

In [61]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [63]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [64]:
x>=3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [65]:
x<=3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [66]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [67]:
x!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [68]:
2*x ==24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [69]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [71]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [72]:
np.sum(x<=3) # True 是1，False 是0

4

In [74]:
np.count_nonzero(x<=3) # # True 是1，False 是0

4

In [75]:
np.any(x==0)

True

In [77]:
np.any(x<0)

False

In [78]:
np.all(x>=0)

True

In [79]:
np.all(x>0)

False

In [80]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
np.sum(X%2 ==0)

8

In [82]:
np.sum(X%2==0,axis =1)  # 每行

array([2, 2, 2, 2])

In [83]:
np.sum(X%2 ==0,axis = 0)

array([4, 0, 4, 0])

In [84]:
np.all(X>0,axis = 1)

array([False,  True,  True,  True])

In [85]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [88]:
np.sum((x>3)&&(x<10))  # 条件运算符

SyntaxError: invalid syntax (<ipython-input-88-3a57998567a8>, line 1)

In [89]:
np.sum((x>3)&(x<10))  # 位运算符

6

In [90]:
np.sum((x%2==0)|(x>10))

11

In [91]:
np.sum(~(x==0))

15

In [92]:
x[x<5]

array([0, 1, 2, 3, 4])

In [93]:
x[x%2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [94]:
X[X[:,3]%3 ==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

### 空矩阵与空向量

In [33]:
i = np.array([[]])
i

array([], shape=(1, 0), dtype=float64)

In [34]:
i.shape

(1, 0)

In [35]:
i.ndim

2

In [36]:
d = np.array([])
d

array([], dtype=float64)

In [37]:
d.ndim

1

In [38]:
d.shape

(0,)