In [2]:
import numpy as np  # 别名

In [4]:
np.__version__  # 查看 np的版本

'1.14.3'

 ### python list 的特点

In [5]:
l = [i for i in range(10)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
l[5]

5

In [8]:
l[5] = "Macine Learning"  # 更改元素的数值 list的元素可以是各种类型，但是效率低
l

[0, 1, 2, 3, 4, 'Macine Learning', 6, 7, 8, 9]

In [2]:
import array

arr = array.array("i",[i for i in range(10)])  # i 代表整型  限定类型，array中只能存放一种类型
print(type(arr))
arr

<class 'array.array'>


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[5] = "4"

TypeError: an integer is required (got type str)

### numpy.array

In [13]:
nparr = np.array([i for i in range(10)])
print(type(nparr))
nparr

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[5] = 80
nparr

array([ 0,  1,  2,  3,  4, 80,  6,  7,  8,  9])

In [14]:
nparr[5] = "ml"

ValueError: invalid literal for int() with base 10: 'ml'

In [17]:
nparr.dtype

dtype('int32')

In [18]:
nparr[5] = 80.0
nparr

array([ 0,  1,  2,  3,  4, 80,  6,  7,  8,  9])

In [19]:
nparr.dtype 

dtype('int32')

In [20]:
nparr[5] = 80.1  # 隐式转换
nparr

array([ 0,  1,  2,  3,  4, 80,  6,  7,  8,  9])

In [21]:
nparr.dtype

dtype('int32')

In [22]:
nparr2 = np.array([1,2,3.0])  # 用list创建一个array ，元素有浮点数，默认是
nparr2.dtype

dtype('float64')

In [23]:
nparr2[4] = 4  # 赋值语句并没有添加功能
nparr2

IndexError: index 4 is out of bounds for axis 0 with size 3

In [24]:
a = [1,2,3]
a[3] = 4

IndexError: list assignment index out of range

In [25]:
nparr2[2] = 3
nparr2

array([1., 2., 3.])

In [27]:
nparr2.dtype

dtype('float64')

In [30]:
nparr3 = np.arange(1,10,2)
nparr3

array([1, 3, 5, 7, 9])

In [34]:
nparr3[4] = "9"  # 隐式转换
nparr3.dtype

dtype('int32')

In [35]:
nparr3[4] = "haha"
nparr3.dtype

ValueError: invalid literal for int() with base 10: 'haha'