### 使用scikit-learn中的kNN

In [1]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [2]:
raw_data_X= [ [3.39,2.33],    
              [3.11,1.78],
              [1.34,3.36],
              [3.58,4.68],
              [2.28,2.86],
              [7.42,4.69],
              [5.74,3.53],
              [9.17,2.51],
              [7.79,3.42],
              [7.93,0.79]
             ]                     # 注意不要出错，多加一个逗号导致维度不匹配，二维列表
raw_data_y = [0,0,0,0,0,1,1,1,1,1]  
x_train = np.array(raw_data_X)  # 矩阵
y_train = np.array(raw_data_y)  # 向量
x = np.array([8.09,3.36])  # 向量

In [3]:
kNN_classifier = KNeighborsClassifier(n_neighbors = 6)
kNN_classifier.fit(x_train,y_train)  # 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [4]:
y_predict = kNN_classifier.predict(x)   # 将要预测是一个矩阵  返回一个向量
y_predict                        

ValueError: Expected 2D array, got 1D array instead:
array=[8.09 3.36].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [5]:
x = x.reshape(1,-1)
x

array([[8.09, 3.36]])

In [6]:
y_predict = kNN_classifier.predict(x)
y_predict

array([1])

In [7]:
y_predict[0]

1

### 重新整理我们的kNN代码

In [8]:
%run playML\test.py  # 关于路径    运行文件同级的playML

hello world,hahah


In [9]:
%run playML\kNN.py

In [10]:
knn_clf = KNNClassifier(k=6)

In [11]:
knn_clf.fit(x_train,y_train)  # call    __repr__(self) 函数

hello KNN(k=6)

In [12]:
X_predict = x
X_predict

array([[8.09, 3.36]])

In [13]:
y_predict = knn_clf.predict(X_predict)
y_predict

array([1])

In [14]:
y_predict[0]

1