In [27]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [29]:
iris = datasets.load_iris()   # 
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [30]:
X = iris.data
y = iris.target
print(type(X),type(y))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [31]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [32]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
X.shape  # 矩阵

(150, 4)

In [34]:
y.shape  # 向量

(150,)

### train_test_split

In [35]:
len(X)  # 矩阵的行，

150

In [36]:
#test
a = np.arange(16).reshape(2,8)  # len()显示的是矩阵的行
len(a)

2

In [37]:
#test
np.random.permutation(3)  # 随机乱序生成一个小于给定数值的array  向量

array([0, 1, 2])

In [38]:
shuffle_indexes = np.random.permutation(len(X))  # 随机生成一个小于给定数值的序列
shuffle_indexes  # 乱序的行号

array([ 87, 121,  45, 140,  31,  23,   3, 142,  88, 111,  86,  78, 149,
        40, 108,  85,  16,  21, 131,  81,  39,  95,  66,  38,   5,   6,
        61,   1, 148,  93,  63,  11,  24,  71, 113,  83,  76,  17,  80,
       129,  33,  64,  15, 101,  62,  14,  41,  72,  50,  26,   8,  19,
        12,  10,  46,  36,  49,  30,  77,  91,   7, 139, 124,  52, 132,
        48, 103, 102, 130,  99,   9,  92,  22, 137, 145, 116, 125, 126,
        57, 143,  94, 127,   0, 138, 112,  34, 105,  18,  90,  32,  43,
        51,  69,  29,  20,  98,  55,  54,  84,  59,  58, 146,  28,   2,
        67, 106,  70,  42, 135,  60,  47, 120, 114, 144,  53, 122, 115,
        75,  37,  44, 107,  65,  68, 136,   4,  56,  97, 147,  25,  79,
        27, 110,  73, 109, 123, 134,  96, 119, 100,  35,  89,  82,  13,
       104, 117, 128,  74, 118, 141, 133])

In [39]:
test_ratio = 0.2
test_size = int(len(X)*test_ratio)
test_size

30

In [40]:
# test
int(3.9)  # 截取

3

In [41]:
test_indexes = shuffle_indexes[:test_size]   # 取前三十个0-29
train_indexes = shuffle_indexes[test_size:]  # 30-149 后120
test_indexes

array([ 87, 121,  45, 140,  31,  23,   3, 142,  88, 111,  86,  78, 149,
        40, 108,  85,  16,  21, 131,  81,  39,  95,  66,  38,   5,   6,
        61,   1, 148,  93])

In [42]:
X_train = X[train_indexes]  #fancy index
y_train = y[train_indexes]

X_test = X[test_indexes]  #  fancyindex  取出对应的行
y_test = y[test_indexes]
X_test.shape

(30, 4)

In [43]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


### 使用我们的算法

In [44]:
from playML.model_selection import train_test_split

In [45]:
X_train,X_test,y_train,y_test= train_test_split(X,y)  # X是数据，矩阵， y是标签向量
X_train

array([[5.8, 2.7, 4.1, 1. ],
       [4.8, 3.4, 1.6, 0.2],
       [5. , 2. , 3.5, 1. ],
       [6.7, 3. , 5. , 1.7],
       [5.7, 2.5, 5. , 2. ],
       [4.6, 3.1, 1.5, 0.2],
       [6.4, 2.9, 4.3, 1.3],
       [5.8, 4. , 1.2, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [5.5, 2.5, 4. , 1.3],
       [4.6, 3.4, 1.4, 0.3],
       [5.4, 3.9, 1.3, 0.4],
       [4.9, 2.4, 3.3, 1. ],
       [7.7, 2.8, 6.7, 2. ],
       [5.4, 3. , 4.5, 1.5],
       [5.7, 3.8, 1.7, 0.3],
       [6.2, 2.8, 4.8, 1.8],
       [5. , 3.4, 1.5, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 2.9, 5.6, 1.8],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 2.7, 5.3, 1.9],
       [6.1, 2.6, 5.6, 1.4],
       [6.5, 2.8, 4.6, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.5, 3.2, 5.1, 2. ],
       [5. , 3.2, 1.2, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [7.1, 3. , 5.9, 2.1],
       [5.8, 2.7, 5.1, 1.9],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 3.5, 1.4, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [6.9, 3

In [46]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


In [47]:
#test
a = train_test_split(X,y)
type(a)     # 返回多个元素时，打包成一个元组

tuple

In [49]:
from playML.kNN import KNNClassifier  # 

In [50]:
my_knn_clf = KNNClassifier(k=3)

In [51]:
my_knn_clf.fit(X_train,y_train)  # 训练 拟合fit

hello KNN(k=3)

In [52]:
y_predict = my_knn_clf.predict(X_test)  # 预测

In [53]:
y_predict

array([1, 1, 1, 2, 1, 1, 0, 2, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0,
       1, 2, 0, 2, 0, 0, 1, 2])

In [54]:
y_test

array([1, 1, 1, 2, 1, 1, 0, 2, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 0, 0, 0, 0,
       1, 2, 0, 2, 0, 0, 1, 2])

In [55]:
len(y_test)

30

In [56]:
sum(y_predict == y_test)

30

In [57]:
sum(y_predict == y_test)/len(y_test)

1.0

### sklearn 中的train_test_split

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 666)  # test的百分比，随机种子

In [71]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(120, 4) (120,)
(30, 4) (30,)


In [72]:
# test
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
ind = [0,4]
a[ind]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

### test

In [58]:
a = np.arange(16).reshape(4,4)

In [59]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
b=[[1,3]]

In [63]:
a[b,1:]

array([[[ 5,  6,  7],
        [13, 14, 15]]])

In [36]:
np.random.seed(3)
a = np.random.randint(300)
b = np.random.permutation(100)
print(a,b)

152 [94 68  6 65 73 84 99 42 25 15 78  9 97 98 34 76 82 23 59 45 93 12  8  4
 80 87 17 83 47 50 30  5 13 31 89 11 58 86 32 40 16 27 35 36 70 91 64 77
 75 46 53 71 67 61 18 92 57 96 54 55 28 52 85 79 90 49 88 37 48 33 43  7
 62 24 29 69 51  1 60 63  2 66 22 81 26 14 39 44 20 38 95 10 41 74 19 21
  0 72 56  3]


In [42]:
np.random.seed(3)
a = np.random.randint(300) #相同
b = np.random.permutation(100)# 相同
print(a,b)

152 [94 68  6 65 73 84 99 42 25 15 78  9 97 98 34 76 82 23 59 45 93 12  8  4
 80 87 17 83 47 50 30  5 13 31 89 11 58 86 32 40 16 27 35 36 70 91 64 77
 75 46 53 71 67 61 18 92 57 96 54 55 28 52 85 79 90 49 88 37 48 33 43  7
 62 24 29 69 51  1 60 63  2 66 22 81 26 14 39 44 20 38 95 10 41 74 19 21
  0 72 56  3]


In [43]:
a = np.random.randint(300) #不相同
b = np.random.permutation(100)# 不相同
print(a,b)

44 [77 92 76 94 75 40 90 58 88 29 56 91 70 95  3 37 48 14 25 12  6 41 10 93
 47 80  0 38 34 64 51 84  4 46 85 66 67 11 59 15 55 21 33 54 23 49 31 97
 83 89 17 30 61 73 71 68 72 42 36 28 82 44 13 79 69  5 78 96 26  9 99 24
 74 86  8 53 27 98 60 32 43 57  7 22 81 62 20 87  2 63 18  1 52 45 35 65
 50 39 16 19]


In [24]:
# test
np.random.seed(12)
np.random.permutation(9)

array([8, 7, 0, 4, 3, 2, 1, 5, 6])

In [25]:
np.random.permutation(9)

array([8, 0, 3, 2, 7, 5, 4, 1, 6])

In [26]:
np.random.seed(12)
np.random.permutation(9)

array([8, 7, 0, 4, 3, 2, 1, 5, 6])